version: 0.2

phases:
  pre_build:
    commands:
      # コミットID取得
      - export COMMIT_ID=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      # ECRへのログイン
      - echo Logging in to Amazon ECR
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email
      # ECRリポジトリ指定（dev環境ではおそらくbuild環境で環境変数登録されているため不要）
      - export IMAGE_REPO_URL1="168602217529.dkr.ecr.ap-northeast-1.amazonaws.com/smcc-batch-test-repository"
      # taskdefの場所指定
      - export TASKDEF_PATH="ecs/batch-taskdef-ita1.json"
  build:
    commands:
      # ビルド開始
      - echo Build started on `date`
      # コンテナイメージのビルド
      - echo Build and Run the Docker image
      - docker build -f cicd/Dockerfile -t $IMAGE_REPO_URL1:$COMMIT_ID .
  # build後
  post_build:
    commands:
      - echo Build completed on `date`
      # ECRへのプッシュ
      - echo Pushing the Docker image
      - docker push $IMAGE_REPO_URL1:$COMMIT_ID
      # タスク定義の格納
      - echo Updating ECS task definition template
      - sed "s|<IMAGE1_NAME>|${IMAGE_REPO_URL1}:${COMMIT_ID}|g" ${TASKDEF_PATH} > taskdef.json
      - echo Registering ECS task definition
      - aws ecs register-task-definition --cli-input-json file://taskdef.json