version: 0.2

phases:
  pre_build:
    commands:
      - HTTP_CODE=$(curl -s -o result.txt -w "%{http_code}" "http://$SONARQUBE_HOST"); cat result.txt; if [ "$HTTP_CODE" != "200" ]; then echo "SonarQubeへ接続できませんでした。"; exit 1; fi
